ports:
- port: 8080
  onOpen: open-preview
- port: 8888
  onOpen: open-browser
tasks:
  - name: echo
    command: "echo 'initiarizing.....'"
  - name: open_upyter
    command: "jupyter notebook --ip=* --NotebookApp.token=''"
