ports:
- port: 8080
  onOpen: open-preview
- port: 8888
  onOpen: open-browser
tasks:
  - name: open_jupyter
    init: "pip install --upgrade pip"
    before: "pip install -r requirements.txt"
    command: "jupyter notebook --ip=* --NotebookApp.token=''"
